# Generated by Django 6.1.1 on 2026-09-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("unique", "Unique"),
                            ("range", "Range"),
                            ("datatype", "Data Type"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
