# Generated by Django 6.1.1 on 2026-09-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0001_initial"),
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("passed_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("quality_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_runs",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("column_name", models.CharField(max_length=255)),
                ("rule_type", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "validation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="validation.validationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
    ]
