services:
  db:
    image: postgres:17
    container_name: dataguard_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dataguard
      POSTGRES_USER: dataguard_user
      POSTGRES_PASSWORD: dataguard_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
